name: CI|CD éƒ¨ç½²æ–‡æ¡£
permissions:
  contents: write
on:
  push:
    branches:
      - main

jobs:
  build:
    name: build nextra
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    if: startsWith(github.ref, 'refs/tags/')
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - name: è¯»å–ä»“åº“å†…å®¹ ğŸ‘“
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: è®¾ç½® Node.js ğŸ¶
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: å®‰è£… pnpm ğŸ¸
        run: npm install --global pnpm

      - name: æ„å»ºæ–‡æ¡£ ğŸ”¨
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          pnpm install
          pnpm run build
          > out/.nojekyll

      - name: release ğŸ˜¶â€ğŸŒ«ï¸
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: 'out/**'
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: éƒ¨ç½²æ–‡æ¡£ ğŸ‘Œ
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: pages
          folder: out